services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      BIND_ADDR: "0.0.0.0:3000"
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend